### ISSUE TITLE
Error on meilisearch:set-index-settings

### ISSUE THREAD

**Issue by martin-ro** [eelcol/laravel-meilisearch#1]
Hey,

wanted to try this package but when I run `php artisan meilisearch:set-index-settings` I get

```log
Eelcol\LaravelMeilisearch\Connector\Collections\MeilisearchIndexCollection::__construct(): 
Argument #1 ($data) must be of type array, MeiliSearch\Contracts\IndexesResults given, 
called in .../vendor/eelcol/laravel-meilisearch/src/Connector/MeilisearchConnector.php 
on line 28 at vendor/eelcol/laravel-meilisearch/src/Connector/Collections/MeilisearchIndexCollection.php:14
```

**Comment by eelcol** [comment]
Thanks for trying out the package! I can see the Meilisearch-php package introduced a breaking change in version 0.24.0:

https://github.com/meilisearch/meilisearch-php/blob/v0.24.0/src/Endpoints/Indexes.php
https://github.com/meilisearch/meilisearch-php/blob/v0.22.0/src/Endpoints/Indexes.php

However this package requires version 0.22 of the Meilisearch-php package. Can you check which version of the `meilisearch/meilisearch-php` package is installed at your end?

I have also updated the readme of this package, stating the compability with Meilisearch. Meilisearch introduced some breaking changes in version 0.28, so this package will not work currently with version 0.28.

**Comment by martin-ro** [comment]
Ah yes, that seems to be the issue. I forked and updated to 0.28 since that's what I'm using in my project. 

Are there any plans to make the package compatible with 0.28?

**Comment by eelcol** [comment]
Yes, I am working on a new version that is compatible with 0.28 and is no longer dependent on the `meilisearch-php` package. I expect to publish this version within a few days.

**Comment by eelcol** [comment]
I just updated the package. Version 1.0.1 works with Meilisearch 0.28. However it is not completely unit-tested yet, so consider this a beta version.

**Comment by martin-ro** [comment]
Thank you, I will try it out this week!
