### ISSUE TITLE
Number of records in hits greater than total count

### ISSUE THREAD

**Issue by vivek-mf** [eelcol/laravel-meilisearch#10]
Number of records in hits are coming greater than total count when using **multi-search** endpoint due to addition of {limit: 1} in  payload for **keepFacetsInMetadata** attributes. 
Found issue on line 43 in Eelcol\LaravelMeilisearch\Connector\Collections\MeilisearchQueryCollection. here you are merging all hits in response, this included hits of **keepFacetsInMetadata** with limit 1, which is not required.

**Comment by eelcol** [comment]
Fixed in 2.3.5 https://github.com/eelcol/laravel-meilisearch/commit/c6f5897b71af6f4e749fa7563b2f11740d1fe404
