### ISSUE TITLE
Disjunctive facets

### ISSUE THREAD

**Issue by martin-ro** [eelcol/laravel-meilisearch#3]
I'm trying to replicate facet behavior like in this example: https://codesandbox.io/s/ms-is-mese9?fontsize=14&hidenavigation=1&theme=dark where facets are recounted with each filter applied but I can't figure out how to write the query for it.

As far as I can see the facets are always counted in total?

For example:

```php
MeilisearchQuery::index('products')
    ->where('categories', '=', 'phones')
    ->keepFacetsInMetadata(function ($q) {
        $q->where('color', '=', 'yellow');
    })
    ->setFacets([
        'color',
        'brand'
    ])
    ->get();
```

All the other `color` facets wouldn't disappear anymore but their count stays the same as if nothing was filtered at all?

Cheers

**Comment by eelcol** [comment]
Thats correct. If you have 2 filters for example color and brand, and you select 1 specific color, you might want to have a count per brand *given* the specific color. However, this would lead to a lot of queries. When using 2 filters, the number of queries is not that high. However, when combining multiple filters this could lead to lots of queries. Thats why I have choosen the current implementation.

So the count of the facets is based on all the `where`-clauses in your query *except* for all the `where`-clauses that are within the `keepFacetsInMetadata` closure. In your example, the facets would return a count per color and per brand of all products in the category `phones`.

I think it is best to wait for Meilisearch implement a solution for this issue in their software. Maybe in a later stage, if they decide not to create something for this, I can think about implementing a solution in this package.

**Comment by eelcol** [comment]
I do like the example you linked however. Not sure however how they worked around this issue. I guess they make a query per facet. I will try to check this out in the next 1-2 weeks and try to build an implementation.

**Comment by martin-ro** [comment]
Great, thanks for looking into it! Let me know if can be of any help.

**Comment by eelcol** [comment]
Really late reply. But Meilisearch has introduced a new endpoint in version 1.1.* that can solve this. I have included this in version 2.1.0 of my package. So this feature is implemented when you use Meilisearch 1.1.* with my package version 2.1.0. Compability with Meilisearch 1.2, 1.3 and 1.4 is also coming.

**Comment by martin-ro** [comment]
Yes, there's a `muli-search` endpoint now. The instantsearch adapter already works with it. I tried this again with v2.3 but got `array_map(): Argument #2 ($array) must be of type array, null given`

```php
MeilisearchQuery::index('products')
    ->where('categories', '=', 'phones')
    ->keepFacetsInMetadata(function ($q) {
        $q->where('color', '=', 'yellow');
        $q->where('size', '=', 'XL');
    })
    ->setFacets([
        'color',
        'brand',
        'size',
    ])
    ->get();
```

Is that how I'm supposed to use this? I don't think the README was updated in between versions so I'm unsure if this is the right approach. Thanks

**Comment by eelcol** [comment]
Let me try to reproduce this. What Meilisearch version are you using?

**Comment by martin-ro** [comment]
I tried this with 1.4 and 1.6 
I saw they are not supported yet but I suspect this is not related to the Meilisearch version.

**Comment by eelcol** [comment]
Okay I have reproduced the issue, working on a fix.

**Comment by eelcol** [comment]
Fixed the bug in the newest version:

https://github.com/eelcol/laravel-meilisearch/commit/df2e35a1087090b55bc7b2921457272b01dfd70d
