### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by zhi8617** [eelcol/laravel-meilisearch#7]
I followed the installation steps
And set up the configuration file

When I try 
php artisan meilisearch:set-index-settings

I get an error

`TypeError

  Eelcol\LaravelMeilisearch\Connector\Models\MeilisearchIndexItem::__construct(): Argument #1 ($data) must be of type array, string given, called in /var/www/html/vendor/eelcol/laravel-meilisearch/src/Connector/Collections/MeilisearchIndexCollection.php on line 19
    at vendor/eelcol/laravel-meilisearch/src/Connector/Models/MeilisearchIndexItem.php:14
  `

I'm using version V2 

I've been trying for a while...
Any ideas?  Thank

**Comment by eelcol** [comment]
Whats your Meilisearch version youre using?

**Comment by zhi8617** [comment]
Thank you for your reply! 
meilisearch version is "pkgVersion" => "1.0.2"


What I want is the keepFacetsInMetadata function that you implemented.
Then I checked the Laravel Scout file and found the raw() function, so I queried it twice and got the data I wanted.


Thank you for your help!

**Comment by gmoigneu** [comment]
@zhi8617 I had the same issue until I realized you must set up the Meili Master Key. If not, it returns an error message that is passed to that class triggering the exception

**Comment by eelcol** [comment]
Version 1.0.2 of Meilisearch is currently not supported. I will bump support of Meilisearch versions in a few weeks. I will check if I can improve the issue when no master key is set up.

**Comment by eelcol** [comment]
Issues fixed in version 2.0.5. You can now use Meilisearch without key and version 1.0.* is officially supported by this package.
